### ISSUE TITLE
examples configs for remote signing

### ISSUE THREAD

**Issue by vchong** [iqlusioninc/tmkms#657]
Hi,

Are there are good references/guides or examples/samples for setting up tmkms for signing via a remote yubihsm, i.e. via https?

Thanks!

**Comment by tony-iqlusion** [comment]
If this is about the `tx-signer` feature, it was removed in #764

**Comment by tony-iqlusion** [comment]
I think what you're after is:

```toml
[[providers.yubihsm]]
adapter = { type = "http", addr = "http://example.com/" }
```

Note that HTTPS is presently unsupported. See https://github.com/iqlusioninc/yubihsm.rs/issues/490
